version: '3.3'

services:
  app:
    container_name: 'app-be'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      - PORT=5000
    command: sh -c "npm install && npm start"

volumes:
  node_modules: